<!-- Kegiatan 5/ Diklat Wirausaha -->
<br><br><br><br>
<div class="container">
            <div class="kegiatan">
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <img src="<?= BASEURL; ?>/images/folio05.jpg" class="img-fluid" alt="Diklat Wirausaha" style="max-width: 800px;">
                        <h1 class="display-4">Diklat Wirausaha</h1>
                        <p class="lead">Diklat Wirausaha adalah kegiatan penerima beasiswa untuk meningkatkan rasa kreatif berwirausaha</p>
                    </div>
                </div>
                <br>
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <p class="lead" style="text-align: justify;">

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere orci nulla, ac finibus sapien sollicitudin eu. Sed ullamcorper lacus sit amet nisl condimentum, sit amet molestie enim facilisis. Aliquam erat volutpat. Etiam varius libero erat, eu consectetur eros tristique quis. Sed venenatis magna sit amet nibh posuere, sed tristique mauris posuere. Etiam rutrum est id urna vulputate, volutpat euismod nisl tristique. Nunc pellentesque eros sed diam tempus, non rutrum nisl imperdiet.

Duis pellentesque neque vel lacus aliquam, ut fringilla nunc mattis. Vivamus ac quam id risus efficitur dictum pulvinar eu sem. Vestibulum ultrices viverra rutrum. Aenean fringilla malesuada dictum. Nunc mattis, nibh vehicula pharetra tempus, est orci venenatis risus, a dignissim mauris nibh quis quam. Maecenas volutpat mattis diam, sed pretium ligula. Proin ut ipsum non risus sodales volutpat.

Nunc luctus quam quis pulvinar pulvinar. Suspendisse condimentum faucibus aliquam. Aliquam accumsan accumsan rutrum. Donec ullamcorper metus vitae lobortis consequat. Aliquam sagittis sem sit amet turpis dignissim tincidunt. Aenean bibendum ultrices tincidunt. Sed nec libero urna. Nam dui diam, malesuada ut nibh id, iaculis ultricies risus. Aliquam ut elit vel ligula facilisis venenatis. Nunc blandit ut ligula vitae congue. In vehicula justo ut est ultricies dapibus. Ut aliquam neque a lacus porta, id suscipit ante elementum. Maecenas malesuada augue lorem, sed condimentum lorem tincidunt vitae. Nulla egestas sollicitudin sem, a pretium arcu efficitur vitae. Aliquam a est urna.

Nam finibus est quis metus gravida vehicula id lacinia justo. Vestibulum ut maximus nulla. Sed malesuada nunc magna, in facilisis enim vehicula a. Quisque laoreet risus mauris, a vehicula massa tincidunt et. Morbi semper, lorem eu consequat pharetra, risus mi iaculis mauris, ut condimentum magna diam non lacus. Proin laoreet erat ac dui accumsan cursus. Nam gravida eros nec dignissim sodales. Cras semper tempus leo at rutrum. Suspendisse dignissim, eros eget condimentum gravida, eros risus congue libero, tincidunt tincidunt justo turpis ut mauris. Integer feugiat, ex vel mollis dapibus, nunc mauris commodo risus, euismod iaculis sapien lectus quis dui. Sed porttitor tincidunt enim at bibendum. Praesent iaculis augue eu nunc placerat, in vestibulum nunc mattis. Aenean pretium nisi euismod, lacinia lectus in, faucibus magna. Nulla maximus nulla a sapien euismod sagittis.

Fusce pharetra est varius euismod vulputate. Mauris convallis blandit egestas. Morbi massa lorem, ullamcorper ac neque lobortis, suscipit vestibulum dolor. Nulla laoreet urna eget nisi elementum lacinia. Curabitur finibus lobortis arcu, sed laoreet ipsum vulputate quis. Mauris quis sem id justo dapibus ultrices. Ut nunc magna, mattis eu elit quis, sodales condimentum dolor. Fusce vitae vulputate lacus. Etiam semper nec massa sit amet laoreet. In hac habitasse platea dictumst. In molestie magna ac erat vulputate, quis pellentesque orci vestibulum.

Vestibulum egestas ipsum at vulputate finibus. Pellentesque quis maximus lacus. Donec lacinia nibh sit amet ullamcorper vestibulum. Ut sed pulvinar risus. Nullam odio nisl, posuere quis leo varius, bibendum tristique sapien. Sed vitae felis luctus, auctor ex id, sollicitudin lacus. Duis pulvinar aliquam nunc, non rutrum ex ultrices id. Suspendisse ut iaculis tortor. Fusce efficitur dolor eget augue sodales suscipit vitae vel turpis. Duis elementum tellus elementum nisi vestibulum, non semper nisi fermentum. Ut porta enim quis nibh pulvinar, sed hendrerit lacus sollicitudin. Sed id lobortis turpis, nec vehicula velit. Quisque placerat ut arcu eget pellentesque. Etiam fringilla felis purus, eget tempus nisi gravida et. Sed pharetra sem non magna pellentesque, at blandit nunc ultricies. Cras neque dui, luctus a mi id, gravida consectetur odio.

Nulla facilisi. Nunc in lorem tempor orci varius tempor. Nulla blandit risus vel urna sodales hendrerit. Vestibulum sit amet blandit odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas efficitur eros est, eget malesuada lacus luctus ac. Etiam pellentesque efficitur erat eget tristique. Nam mollis pulvinar turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum venenatis tempus nunc, in imperdiet elit ultricies ut. In neque mauris, ultrices ac ante tincidunt, dictum eleifend dui.

Donec convallis hendrerit arcu sollicitudin mattis. Curabitur tellus lorem, laoreet non tempus eu, ornare eget dui. Phasellus rhoncus semper maximus. Aenean sagittis ultrices leo et pulvinar. Morbi interdum feugiat laoreet. Pellentesque a interdum turpis. Fusce dignissim tristique mollis. Suspendisse at tortor euismod, varius ipsum in, pellentesque arcu. Aliquam erat volutpat. Curabitur pharetra consectetur sapien id ullamcorper. Donec nisl enim, lobortis eget vestibulum quis, ornare eu orci. Proin eget aliquet metus, gravida accumsan nisi. Vivamus elit odio, lobortis vel ex sed, consequat rhoncus neque.

Cras elementum tortor nunc, a tincidunt felis feugiat vitae. Nullam id tellus vulputate, egestas sem in, sodales enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer in lorem luctus est mattis tempor eu ut ligula. Duis non risus a leo luctus eleifend. Nam sollicitudin suscipit leo sit amet ultricies. Etiam quis leo ultrices, scelerisque augue eget, tristique purus. Phasellus nec felis nec lacus feugiat suscipit. Aenean ullamcorper risus sit amet vehicula feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent mattis commodo consectetur. Cras bibendum laoreet diam id commodo. Donec faucibus enim in arcu semper convallis. Sed sollicitudin libero id orci tristique, sit amet malesuada ex vulputate. Phasellus non porta leo. Praesent nec volutpat eros.

Maecenas in varius eros. Nunc tincidunt finibus lacus id scelerisque. Cras quis pellentesque dolor. Nunc vel consectetur metus, eget auctor erat. Vestibulum bibendum metus libero, vitae sagittis leo bibendum in. Pellentesque sit amet convallis elit. Nam eleifend nisi odio, id facilisis tellus hendrerit a. Quisque tempus turpis non lacus placerat, vitae hendrerit tortor vestibulum. Aliquam consectetur posuere rutrum.

Cras mollis, dui sed mollis tempus, ipsum ipsum finibus nisi, in imperdiet quam augue vitae orci. Praesent ullamcorper, urna eu finibus tempus, ipsum nibh volutpat tortor, et facilisis risus augue in ligula. Vestibulum congue ullamcorper metus, vel auctor ante pretium ac. Mauris at pretium ipsum. Nunc ut fringilla quam. Vivamus feugiat odio commodo, laoreet nunc sed, iaculis erat. Donec pharetra condimentum leo a euismod. Etiam erat sapien, commodo convallis lectus a, interdum faucibus nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet ultricies turpis, at dapibus ipsum. Donec semper dui id velit malesuada efficitur. Nullam tempus nunc eget odio tempus, sed congue nulla scelerisque. Fusce nec elementum felis. In sodales est sed consequat lacinia. Nullam dictum, nibh vel auctor malesuada, diam ligula tincidunt nulla, a accumsan eros ipsum vulputate ipsum. Quisque sodales massa at dolor mattis, eu posuere nulla interdum.

Cras congue eros sed magna dapibus accumsan. Pellentesque quis ultrices quam. Mauris lacinia ipsum ut mauris suscipit, vitae convallis risus mattis. Nam id lacinia lacus, id elementum nisi. Proin purus quam, blandit eu sagittis vitae, hendrerit sit amet turpis. Nulla vitae est ac dolor suscipit tristique. Curabitur a dolor vitae odio elementum dignissim rhoncus eget mauris. Nunc egestas tincidunt sem non facilisis. Duis ut ante malesuada, porttitor turpis eget, pulvinar est. Integer vitae velit nec lectus ullamcorper rutrum eu eu augue. Ut massa nunc, efficitur ac diam ac, malesuada tincidunt nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin vel leo nec eros porta elementum.

Nulla euismod mauris eu odio congue, ut consectetur nunc molestie. In hac habitasse platea dictumst. Maecenas dapibus, neque ut aliquam scelerisque, augue tellus tempus ligula, ac venenatis turpis magna eu arcu. Nunc in cursus nibh. Maecenas accumsan maximus odio, mollis ultricies elit dictum et. Nulla efficitur rutrum urna, vitae ultricies lorem imperdiet ac. Vivamus egestas purus neque, vel congue erat maximus id. Mauris facilisis tincidunt erat id hendrerit. Mauris et ante non erat suscipit elementum eget a purus. Curabitur tincidunt dui at lectus hendrerit, vitae porta justo hendrerit. Maecenas sed lacinia metus, ac mollis dui. </p>
                    </div>
                </div>
            </div>
</div>
