<!-- Kegiatan 4/ Kajian Intelektual -->
<br><br><br><br>
<div class="container">
            <div class="kegiatan">
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <img src="<?= BASEURL; ?>/images/folio04.jpg" class="img-fluid" alt="Kajian Intelektual" style="max-width: 800px;">
                        <h1 class="display-4">Kajian Intelektual</h1>
                        <p class="lead">Kajian Intelektual adalah kegiatan penerima beasiswa untuk menambah wawasan dan berpikir kritis</p>
                    </div>
                </div>
                <br>
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <p class="lead" style="text-align: justify;">
                          Nalar pernah menjadi dewa maha perkasa dunia manusia. Otoritasnya yang termanifestasi melalui proses <em>Renaissance</em> dan <em>Aufklarung</em> telah melengserkan referensi kebenaran manusia Eropa kala itu dari Tuhan dan gereja. Mekanisme nalar telah membawa kita untuk menapaki awan, menyelami samudera, melipat ruang dan waktu. Nalar juga telah menghantarkan pekerjaan manusia semakin hari semakin efisien melalui mesin-mesin industri, hingga operasi algoritma dan lalu lintas data.</p>
                          <p>Namun, perjalan zaman memang selalu membuka topeng-topeng kebusukan. Dewa baru itu pun mulai menunjukkan wajah kebengisan. Salah satu wajah kebengisannya yang paling kelam adalah Nazi dan tentu program pembantaiannya, Holocaust. Nazi memang tidak dibentuk orang-orang bebal yang tidak mampu berpikir, melainkan cendekiawan cerdas jenius. Wagner dan Nietzche bisa menjadi contoh salah dua tokoh intelektual di balik skenario bangkitnya fasisme Nazi. Pada tahun 1939 pun, beberapa tokoh di perguruan tinggi, ahli hukum, dokter dan para pimpian perusahaan di Jerman berbondong-bondong memberi dukungan pada Nazi<a href="#_ftn1" name="_ftnref1">[1]</a>.</p>
                          <p>Lantas, bagaimana mungkin nalar yang awalnya dianggap begitu mulia mampu menimbulkan fasisme yang bengis dan Holocaust, sebuah pembantaian yang begitu kejam? Penjelasan Ziygmunt Bauman, seorang ‘Nabi Postmodernisme’, kiranya dapat menerangkan kegelapan fenomena ini. Kritik Bauman terhadap masyarakat modern menangkap adanya semacam ambivalensi, ‘anak haram’ modernitas. Ambivalensi adalah “obsesi yang besar terhadap desain dan tatanan”<a href="#_ftn2" name="_ftnref2">[2]</a>. Suatu hasil upaya masyarakat modern untuk menciptakan kategori-kategori, menyusun heterogenitas dan keterserakan menjadi pola dan keteraturan. Ambisi kategorisasi ini yang pada akhirnya melahirkan kelompok ketiga, ‘<em>the Stranger’.</em></p>
                          <p>‘<em>The Stranger’</em> adalah orang ketiga yang merupakan manifestasi dari bahaya yang mengancam tatanan. Dalam fasisme Jerman, kaum Yahudi adalah ras inferior yang harus dimusnahkan agar tujuan superioritas bangsa Jerman tercapai. Pandangan inilah yang melahirkan Holocaust. Pertanyaannya, apakah Holocaust adalah hasil dari sebuah nalar atau sebuah ketergesa-gesaan emosi belaka? Jawabannya bisa dua-duanya.</p>
                          <p>Di sini, sampailah kita pada posisi untuk menggugat nalar atau lebih tepatnya menggugat pandangan umum tentang nalar. Donald Calne, seorang ahli neurologi, menyampaikan poin yang sangat penting untuk memahami nalar dengan benar. Kesimpulannya, nalar itu netral adalah benar. Namun, justru karena kenetralannya, nalar hanya dapat menjawab pertanyaan “Bagaimana”, tapi tak mampu menjawab pertanyaan “Mengapa”. Nalar akan membantumu mencari cara agar bisa menurunkan berat badan, tapi alasan mengapa kau ingin menurunkan berat badan bukanlah dorongan nalar, melainkan dorongan emosional. Nalar bisa mencarikanmu alternatif-alternatif agar sukses mendapatkan perhatian gebetan, tetapi mengapa kau ingin mendekati si doi, tidak bisa dijawab oleh nalar.</p>
                          <p>Begitu pula Holocaust terjadi, alasan menganggap kaum Yahudi, juga beberapa kaum lain seperti kaum Roma Gipsi dan beberapa bangsa Slavia, sebagai ras inferior mungkin bukan kesimpulan nalar yang rasional, tetapi setelah anggapan ras inferior diakui kemudian dihubungkan dengan tujuan fasisme Nazi, maka pembantaian terhadap mereka adalah hasil nalar. Tentu saja Holocaust bukan satu-satunya, jutaan korban perang dunia, bom atom Hiroshima dan Nagasaki, perang teluk, dan kebengisan-kebengisan lainnya tidak dapat dimungkiri adalah hasil upaya nalar untuk mencapai ambisi dan tujuan-tujuan. Mungkin fenomena tersebut adalah bukti sebuah pernyataan paradoks yang disampaikan oleh Herbert Marcuse: ‘<em>irrationality of rationality’.</em></p>
                          <p>Berbagai fakta kejam dari sejarah kelam nalar tersebut akhirnya melahirkan zaman baru, zaman dimana rasionalitas bukanlah solusi tunggal peradaban, yaitu zaman yang disebut sebagai ‘<em>postmodernism era’</em>. Dalam era postmodernisme, narasi-narasi besar hasil pemikiran rasionalitas ditolak. Sebaliknya narasi-narasi mini, bahkan yang dihasilkan oleh mistisme lokal atau kebudayaan maupun tradisi, bisa saja diakui kebenaran dan keberlakuannya. <em>Nah</em>, tibalah kita pada pertanyaan yang lebih kompleks: “jikalau nalar dan rasionalitas tak lagi diakui secara absolut, apalagi peran yang dapat dilakukan kaum intelektual?”</p>
                          <p>Merumuskan peran intelektual di era ‘tanpa kepastian’ dan ‘tanpa pijakan’ secara konkret tentu bukan hal mudah. Gairah mencari ilmu yang semakin dimonopoli oleh pragmatisme, mungkin menimbulkan keresahan besar bagi mahasiswa-mahasiswa semacam anggota KSM Eka Prasetya yang berorientasi pada pengembangan potensi nalar: “Usentuk apa menjadi seorang intelektual?” Untuk menjawabnya, ketegasan Edward Said dan kritisisme ala Alois A. Nugroho mungkin bisa menjadi semacam <em>guideline</em> bagi intelektual-intelektual yang tak jelas arah pacunya.</p>
                          <p>Edward W. Said secara lugas menyatakan bahwa tugas intelektual adalah menyampaikan kebenaran pada kekuasaan. Konsep kebenaran dalam hal ini bukan kebenaran ambigu yang dihasilkan oleh narasi-narasi besar pemikir modern, melainkan kebenaran tersembunyi di sudur-sudut marjinalitas. Oleh karena itu, kata Said, peran intelektual adalah peran oposisi yang mempertanyakan kebenaran <em>status quo</em> sekaligus mengartikulasikan kebenaran di balik suara yang terbungkam.<a href="#_ftn3" name="_ftnref3">[3]</a></p>

                    </div>
                </div>
            </div>
</div>
